name: Android Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
              
      - name: Decode app.properties file
        env:
          SECRETS_PROPERTIES: ${{ secrets.PROPERTIES_FILE }}
        run: echo "$SECRETS_PROPERTIES" |
          base64 -d > app/src/main/assets/app.properties
        
      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble
